### PR TITLE
retrieve player instance if you dont know their uuid

### PR DESCRIPTION
**Pull request by iAtomPlaza**

### CODE REVIEW

**Comment by Sandertv** [comment]
I'm not sure if we should allow different casing in this method, maybe just checking if their exact name matches would be safer?

**Comment by iAtomPlaza** [comment]
I'm not sure how that would be a problem. Perhaps you could elaborate? Cause it's something I use all the time in my commands where a parameter is a players name and I personally find it easier to not wory about case. As I mentioned, please enlighten me as to how this may be a problem?

**Comment by Sandertv** [comment]
As commands will have a dedicated `Target` type that will take care of that stuff, we should probably keep this case sensitive as it is generally a good idea to be strict rather than lenient.

**Comment by iAtomPlaza** [comment]
Alright, I'll make another commit

**Pull request merged**
