### PR TITLE
Fix runtime error: integer divide by zero

### PR DESCRIPTION
**Pull request by WangYneos**
if p > 32, 32 / int(p) = 0, cause server panic

### CODE REVIEW

**Comment by Sandertv** [comment]
This is just a result of a problem that shouldn't exist in the first place. Do you have steps to reproduce?

**Comment by WangYneos** [comment]
I tried to decode BDS's chunk by using this library, and i got this error

**Comment by Sandertv** [comment]
Decode it in what way? Also if you get this error, just silently ignoring it will not fix that. This is not a solution, it just hides the problem.

**Comment by WangYneos** [comment]
图片
图片

**Comment by WangYneos** [comment]
Just decode single chunk by using `((SubChunk*)SubChunk_Iter_Begin)->serialize(*(IDataOutput*)varout, 0);  ` will be able to reproduce it

**Comment by Sandertv** [comment]
Is this a chunk sent over network or on disk?

**Comment by WangYneos** [comment]
send over network

**Comment by WangYneos** [comment]
[9 2 252 8 0 16 17 17 17 65 68 39 0 17 17 17 17 65 68 39 0 0 17 17 17 65 68 39 0 16 17 17 17 65 68 36 0 0 16 17 17 68 116 34 0 16 17 17 17 68 116 34 0 16 17 17 17 65 116 34 0 0 17 17 17 68 116 34 0 17 17 17 17 68 116 34 0 17 17 17 17 70 68 196 0 0 16 17 97 65 68 40 0 16 17 17 85 69 68 153 0 17 17 81 85 21 17 17 0 0 16 81 85 85 17 17 0 0 16 81 85 85 17 17 0 0 17 17 85 21 17 17 0 0 17 17 17 65 68 170 0 0 17 17 17 65 68 39 0 0 17 17 17 65 68 39 0 17 17 17 17 65 68 36 0 16 17 17 17 68 116 34 0 17 17 17 17 68 116 34 0 0 17 17 17 68 116 34 0 16 17 17 17 68 116 34 0 0 17 17 17 65 116 34 0 17 17 17 97 65 68 36 0 0 16 17 102 22 17 97 0 16 17 17 17 17 17 17 0 0 17 17 81 17 17 17 0 17 17 17 85 21 17 17 0 17 17 17 85 21 17 17 0 16 17 17 85 21 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 68 116 34 0 17 17 17 17 65 116 34 0 17 17 17 17 17 17 178 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 97 0 0 16 17 17 17 17 97 0 17 17 17 17 17 17 17 0 16 17 17 49 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 81 21 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 19 0 17 17 17 17 17 97 17 0 17 17 17 17 17 97 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 22 0 0 17 17 17 17 17 22 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 97 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 102 17 17 17 17 0 17 17 102 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 102 17 17 97 22 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 0 17 17 17 17 17 19 0 17 17 17 17 17 97 19 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 19 0 0 16 17 17 17 17 19 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 17 17 17 17 17 17 17 0 17 17 17 17 17 17 17 0 0 16 17 17 17 29 17 0 16 17 17 17 17 29 17 0 17 17 17 17 17 17 17 0 16 17 17 17 17 17 17 0 0 16 17 17 17 17 17 0 0 16 17 17 17 17 17 32 10 0 8 4 110 97 109 101 17 109 105 110 101 99 114 97 102 116 58 98 101 100 114 111 99 107 10 6 115 116 97 116 101 115 1 14 105 110 102 105 110 105 98 117 114 110 95 98 105 116 0 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 19 109 105 110 101 99 114 97 102 116 58 100 101 101 112 115 108 97 116 101 10 6 115 116 97 116 101 115 8 11 112 105 108 108 97 114 95 97 120 105 115 1 121 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 13 109 105 110 101 99 114 97 102 116 58 97 105 114 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 31 109 105 110 101 99 114 97 102 116 58 100 101 101 112 115 108 97 116 101 95 100 105 97 109 111 110 100 95 111 114 101 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 14 109 105 110 101 99 114 97 102 116 58 99 108 97 121 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 16 109 105 110 101 99 114 97 102 116 58 103 114 97 118 101 108 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 32 109 105 110 101 99 114 97 102 116 58 100 101 101 112 115 108 97 116 101 95 114 101 100 115 116 111 110 101 95 111 114 101 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 15 109 105 110 101 99 114 97 102 116 58 119 97 116 101 114 10 6 115 116 97 116 101 115 3 12 108 105 113 117 105 100 95 100 101 112 116 104 0 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 22 109 105 110 101 99 114 97 102 116 58 98 105 103 95 100 114 105 112 108 101 97 102 10 6 115 116 97 116 101 115 1 17 98 105 103 95 100 114 105 112 108 101 97 102 95 104 101 97 100 1 8 17 98 105 103 95 100 114 105 112 108 101 97 102 95 116 105 108 116 4 110 111 110 101 3 9 100 105 114 101 99 116 105 111 110 2 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 22 109 105 110 101 99 114 97 102 116 58 98 105 103 95 100 114 105 112 108 101 97 102 10 6 115 116 97 116 101 115 1 17 98 105 103 95 100 114 105 112 108 101 97 102 95 104 101 97 100 0 8 17 98 105 103 95 100 114 105 112 108 101 97 102 95 116 105 108 116 4 110 111 110 101 3 9 100 105 114 101 99 116 105 111 110 2 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 22 109 105 110 101 99 114 97 102 116 58 98 105 103 95 100 114 105 112 108 101 97 102 10 6 115 116 97 116 101 115 1 17 98 105 103 95 100 114 105 112 108 101 97 102 95 104 101 97 100 0 8 17 98 105 103 95 100 114 105 112 108 101 97 102 95 116 105 108 116 4 110 111 110 101 3 9 100 105 114 101 99 116 105 111 110 6 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 20 109 105 110 101 99 114 97 102 116 58 109 111 115 115 95 98 108 111 99 107 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 20 109 105 110 101 99 114 97 102 116 58 99 97 118 101 95 118 105 110 101 115 10 6 115 116 97 116 101 115 3 17 103 114 111 119 105 110 103 95 112 108 97 110 116 95 97 103 101 46 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 28 109 105 110 101 99 114 97 102 116 58 100 101 101 112 115 108 97 116 101 95 105 114 111 110 95 111 114 101 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 23 109 105 110 101 99 114 97 102 116 58 102 108 111 119 105 110 103 95 119 97 116 101 114 10 6 115 116 97 116 101 115 3 12 108 105 113 117 105 100 95 100 101 112 116 104 0 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 18 109 105 110 101 99 114 97 102 116 58 99 111 97 108 95 111 114 101 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 64 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 10 0 8 4 110 97 109 101 13 109 105 110 101 99 114 97 102 116 58 97 105 114 10 6 115 116 97 116 101 115 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0 10 0 8 4 110 97 109 101 15 109 105 110 101 99 114 97 102 116 58 119 97 116 101 114 10 6 115 116 97 116 101 115 3 12 108 105 113 117 105 100 95 100 101 112 116 104 0 0 3 7 118 101 114 115 105 111 110 134 200 134 17 0]
Chunk Data

indicesPerUint32: 8 p:4
indicesPerUint32: 0 p:51

**Comment by WangYneos** [comment]
图片

**Comment by Sandertv** [comment]
However you are encoding these subchunks and the way dragonfly decodes them are not compatible. This panic occurs under circumstances when the encoding/decoding are incompatible, as a palette size of 32 is simply not valid. I can't really help too much with this and I do not know if it's a dragonfly bug in the first place. These functions are unexported and therefore should not be used by the end-user in the first place.

While panicking under this circumstance isn't a very good thing, that is not necessarily an issue here as no malicious actor would be able to make this crash, given clients do not send these chunks. This fix just hides the issue and I don't think that's a good thing. I will close this PR because of that.

I do recommend you consider joining our Discord, we might be able to help you get this working there.

**Comment by WangYneos** [comment]
thanks for your help

**Pull request closed without merging**
