### PR TITLE
Add fire methods to the living interface

### PR DESCRIPTION
**Pull request by Prim69**

### CODE REVIEW

**Comment by Sandertv** [comment]
Why is this change necessary?

**Comment by Prim69** [comment]
Living items can be set on fire (discussed with tal on discord)

**Comment by Sandertv** [comment]
Right, but what is the actual use of this? There's hardly a point in adding methods to an interface if those methods just aren't used anywhere.

**Comment by Sandertv** [comment]
Besides, there are also entities that are not `Living` that can also be set on fire (arrows, snowballs), so baking this into the `Living` interface wouldn't necessarily make sense.

**Comment by Sandertv** [comment]
I don't see the point of adding an interface if it's not used in dragonfly.

**Comment by T14Raptor** [comment]
Actually, there already is an interface for it

https://github.com/df-mc/dragonfly/blob/master/server/entity/flammable.go

**Comment by T14Raptor** [comment]
Closing due to an `entity.Flammable` interface already existing.

**Pull request closed without merging**
