### PR TITLE
block/lava.go: set on fire for 8 seconds instead of 15.

### PR DESCRIPTION
**Pull request by Dasciam**
On fire time after being inside the lava changed from some version to 8 seconds

### CODE REVIEW

**Comment by DaPigGuy** [comment]
When was this changed?

**Comment by Dasciam** [comment]
> When was this changed?

Like I said I don't know what version it was changed in, but you can test it on the newest version and see that on fire time is clearly not 15 seconds

**Comment by Dasciam** [comment]
Also sorry for the confusion, changed the PR description

**Comment by Dasciam** [comment]
Closed as this is a bug

**Pull request closed without merging**
