### PR TITLE
Introduce new form API

### PR DESCRIPTION
**Pull request by Blackjack200**
This new form API is much easiler to use and simpler than old one

# Examples
## Menu
```go
f := form.NewMenu("Choose an item").
	WithBody("You can choose an item").
	Button(form.NewButton("Diamond Sword", "textures/items/diamond_sword.png"), func(s form.Submitter) {
		s.(*player.Player).Message("You selected diamond sword")
	}).
	Button(form.NewButton("Egg", "textures/items/egg.png"), func(s form.Submitter) {
		s.(*player.Player).Message("You selected egg")
	}).
	OnClose(func(s form.Submitter) {
		s.(*player.Player).Message("Why don't choose")
	})
p.SendForm(f)
```

# Modal

```go
f := form.NewModal().
	WithBody("Are you sure?").
	WithButton1(form.YesButton(), nil).
	WithButton2(form.NoButton(), func(s form.Submitter) {
		s.(*player.Player).Message(":(")
	})
p.SendForm(f)
```

# Custom
```go
f := form.NewCustom("Feedback").
	WithElements(
		form.NewInput("Reason", "", "reason"),
		form.NewToggle("???", false),
	).OnSubmit(func(p form.Submitter, reason string, satisfied bool) {})
p.SendForm(f)
```

### CODE REVIEW

**Comment by Blackjack200** [comment]
I think this style of custom form should be better

```go
f := form.NewCustom("Feedback").
	WithElements(
		form.NewInput("Reason", "", "reason"),
		form.NewToggle("??", false),
	).OnSubmit(func(p form.Submitter, reason string, satisfied bool) {
		p.(*player.Player).Messagef("Reason: %v, Satisfied: %v", reason, satisfied)
	})
p.SendForm(f)
```

**Comment by smartcmd** [comment]
really cool!

**Comment by riccskn** [comment]
Interessing

**Comment by JustTalDevelops** [comment]
As discussed on Discord, I think it might make sense to make this its own library and support the structured approach by default. I do agree that menu forms are designed a bit weirdly, however I think that can be resolved without an entire revamp like this.

**Comment by Sandertv** [comment]
As explained in the comment above, it is now possible to implement forms in outside libraries. We are not currently looking to overhaul forms entirely. A change to menu forms is something we will look at in the future.

**Pull request closed without merging**
