### PR TITLE
Add *Player.SetHealth()

### PR DESCRIPTION
**Pull request by RestartFU**
I'm not sure if that's the best way to do it but I still did it.

### CODE REVIEW

**Comment by RestartFU** [comment]
oh shit I actually didn't test to add health lol I only did to remove it I think

**Comment by RestartFU** [comment]
nevermind just tested, it works fine I think

**Comment by RestartFU** [comment]
should I close this PR

**Comment by Sandertv** [comment]
Closing this for the reasons mentioned in #284.

**Pull request closed without merging**
