### PR TITLE
Support for the default flame particle

### PR DESCRIPTION
**Pull request by Prim69**
The current flame particle is actually a colored flame, the difference can be seen here.
image
The top particle is particle.Flame, while the bottom particle is an orange particle.ColouredFlame

image
image

### CODE REVIEW

**Comment by T14Raptor** [comment]
They do look noticeably different though even when putting the color to orange

**Comment by JustTalDevelops** [comment]
Yeah, side by side comparison:
image

I think there should be an option for the actual flame particle, as the coloured flame particle looks much more dull compared to it which is not ideal for everyone.

**Comment by Prim69** [comment]
is this alright?

**Review by Sandertv — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
